#!/bin/sh
# chkupd
# Copyright 2021 <kreato@kreato.dev>
#
# This file is part of chkupd.
#
# chkupd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# chkupd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with chkupd. If not, see <https://www.gnu.org/licenses/>.
VER="2-rc1"

. libchkupd/libchkupd

main() {
    [ -z "$2" ] && echo "error: invalid backends" && exit 1
    [ ! -d "$1" ] && echo "error: please go onto the repository's folder" && exit 1
    echo "chkupd v$VER"
    echo "backends: $2"
    export LOGS=$LOGS
    rm -f $LOGS
    for i in $(echo "$2" | tr "," "\n"); do
	    if [ -f "libchkupd/backends/"$i"_chkupd" ]; then
	     	"$i"_chkupd "$1" "$3"
	    else
		echo "warning: $i is not an available backend, skipping"
	    fi
    done
    exit $ERR
}

case "$1" in
    "-h")
        echo "usage: chkupd [PACKAGE_DIR] [BACKENDS] [ARGS]"
    ;;
    "-v")
        echo "chkupd - v$VER"
    ;;
    *)
        main "$@"
    ;;
esac
