#!/bin/sh
# chkupd
# Copyright 2021 <kreato@kreato.dev>
#
# This file is part of chkupd.
#
# chkupd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# chkupd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with chkupd. If not, see <https://www.gnu.org/licenses/>.
VER=1.2

version() {
    echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; # From https://stackoverflow.com/a/37939589
}

main() {
    echo "checking package $1"
    [ ! -d "$1" ] && echo "error: please go onto the repository's folder" && exit 1
    echo "connecting to arch repositories"
    UPSTREAM_VER="$(curl -s https://archlinux.org/packages/search/json/?name=$1 | jq '.results[0].pkgver' -r | cut -f1 -d"-")"
    . "$1/run"
    if [ "$(version $VERSION)" -ge "$(version $UPSTREAM_VER)" ]; then
        echo "the package is uptodate!"
    elif [ "$UPSTREAM_VER" = "null" ] || [ "$UPSTREAM_VER" = "" ]; then
        echo "the package didn't have a version (possibly not on the repos), skipping"
        exit 0
    else
        echo "the package is not uptodate!"
        echo "upstream version: $UPSTREAM_VER"
        echo "local version: $VERSION"
    fi
    case "$2" in
        "-u")
            [ "$FORCED_UPDATE" != "1" ] && [ "$VERSION" = "$UPSTREAM_VER" ] && echo "error: upstream and local version are the same, FORCED_UPDATE=1 to skip" && exit 1
            echo "Updating to upstream..."
            sed -i "s/VERSION=.*/VERSION=$UPSTREAM_VER/g" $1/run
            [ -d "tmp" ] && rm -rf tmp
            mkdir tmp 
            cd tmp || exit 1
            . ../$1/run
            echo "$SOURCES" | cut -d ';' -f 1 | while read -r line
            do
                filename=$(basename $line)
                echo "$line"
                wget "$line"
                sum="$(sha256sum "$filename");"
                printf "$sum" >> tmp.sum
            done
            sum=$(cat tmp.sum)
            echo $sum
            sed -i "s/SHA256SUM=.*/SHA256SUM=\x22$sum\x22/g" ../$1/run
            cd .. || exit 1
            rm -rf tmp
            echo "Updated to $UPSTREAM_VER."
            echo "Please test it before publishing."
        ;;
    esac
}

case "$1" in
    "-h")
        man chkupd
    ;;
    "-v")
        echo "chkupd - v$VER"
    ;;
    *)
        main "$@"
    ;;
esac
