#!/bin/sh
# nyaa_chkupd
nyaa_chkupd() {
	echo "nyaa_chkupd: comparing to nyaa-repo"
	. "$1/run" || exit 1
	wget https://raw.githubusercontent.com/kreatolinux/nyaa-repo/master/$NAME/run -O /tmp/tmp.run > /dev/null 2>&1
	. /tmp/tmp.run || exit 1
	UPSTREAM_VERSION="$VERSION"	
	if [ -d "$2" ]; then
		LIBCHKUPD_BIN_PATH="$2/$NAME-bin"
		. "$2/$NAME-bin/run" || exit 1
	else
		LIBCHKUPD_BIN_PATH="$NAME-bin"
		. "$NAME-bin/run" || exit 1
	fi
	
	if [ "$(version $VERSION)" -ge "$(version $UPSTREAM_VERSION)" ]; then
		echo "nyaa_chkupd: the package is uptodate compared to nyaa-repo!"
	else
		echo "nyaa_chkupd: the package is not uptodate!"
		
		if [ "$LOGS" = "on" ]; then
			echo "nyaa_chkupd: $NAME upstream ver: $UPSTREAM_VERSION local: $VERSION" >> out.txt
		fi
		
		echo "nyaa_chkupd: upstream version: $UPSTREAM_VERSION"
		echo "nyaa_chkupd: local version: $VERSION"

		if [ "$UPDATEPKG" = "on" ]; then
			echo "nyaa_chkupd: updating package $NAME"
			sed -i "s/$VERSION/$UPSTREAM_VERSION/" "$LIBCHKUPD_BIN_PATH/run"
			echo "nyaa_chkupd: please check if the package works or not"
		fi
		
		export ERR=1
	fi

}
